language: php

os: linux
dist: xenial

services:
  - mysql
  - postgresql
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm

jobs:
  include:
    - php: 7.4
      env: MOODLE_BRANCH=master            DB=pgsql
    - php: 7.4
      env: MOODLE_BRANCH=master            DB=mysqli
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_310_STABLE DB=pgsql
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_310_STABLE DB=mysqli
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_39_STABLE  DB=mysqli
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_38_STABLE  DB=pgsql

    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_37_STABLE  DB=mysqli
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_36_STABLE  DB=pgsql

    - php: 7.2
      env: MOODLE_BRANCH=master            DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=master            DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_310_STABLE DB=pgsql
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_310_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_39_STABLE  DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_35_STABLE  DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_34_STABLE  DB=pgsql

    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_38_STABLE  DB=pgsql
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_37_STABLE  DB=mysqli
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_33_STABLE  DB=mysqli
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_32_STABLE  DB=pgsql NODE_VERSION=8.9

    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_36_STABLE  DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_35_STABLE  DB=mysqli
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_34_STABLE  DB=pgsql

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - export IGNORE_PATHS=moodle/tests/fixtures,moodle/Sniffs

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
